version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanagementtool
    ports:
      - "5441:5441"
    command: ["postgres", "-p", "5441"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
